[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.11.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/urfave/negroni"
  revision = "dae7dc68e5a970eeecdaa7e4191e11d103cb8c1d"

[prune]
  go-tests = true
  unused-packages = true